Repository codeit-sprint-fullstack/3-sprint-mission-fe, pull requests merged in 2024-11, with the labels that each got.

#83 [함헌규] sprint5
  .gitignore
  .storybook/main.js
  .storybook/preview.jsx
  docs/sprint5.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/fonts/PretendardVariable.woff2
  public/icons/DropDown.png
  public/icons/PandaIcon.png
  public/images/common/logo.png
  public/images/common/mobileLogo.png
  public/images/home/2.popular_product.jpg
  public/images/home/3.search_product.jpg
  public/images/home/4.register_product.jpg
  public/images/home/Img_home_bottom.png
  public/images/home/Img_home_top.png
  public/images/home/ic_facebook.png
  public/images/home/ic_instagram.png
  public/images/home/ic_twitter.png
  public/images/home/ic_youtube.png
  public/images/sign/google.png
  public/images/sign/kakaotalk.png
  src/App.jsx
  src/Root.jsx
  src/apis/ProductService.js
  src/apis/axiosInstance.js
  src/components/common/Footer.jsx
  src/components/common/Nav.jsx
  src/components/common/PageIndex.jsx
  src/components/common/RefreshButton.jsx
  src/components/common/Select.jsx
  src/components/products/BestProductContainer.jsx
  src/components/products/Product.jsx
  src/components/products/ProductsBar.jsx
  src/components/products/ProductsContainer.jsx
  src/constants/mediaQuery.js
  src/constants/messages.js
  src/constants/productSortBy.js
  src/constants/propValues.js
  src/constants/url.js
  src/hooks/useProducts.js
  src/hooks/useScreenWidth.js
  src/jotai/atoms/productSearchKeywordState.js
  src/jotai/atoms/productSortByState.js
  src/main.jsx
  src/pages/Products.jsx
  src/stories/PageIndex.stories.jsx
  src/stories/Product.stories.jsx
  src/stories/Select.stories.jsx
  src/theme.js
  src/utils/formatter.js
  vite.config.js
Labels: 매운맛🔥, 최종 제출

#85 [이현우] sprint5
  .editorconfig
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc
  API.md
  JOURNAL.md
  README.md
  app/layout.ts
  app/page.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/fonts/PretendardVariable.woff2
  public/fonts/index.ts
  src/app/layouts/index.tsx
  src/app/styles/globals.css
  src/app/styles/index.ts
  src/app/types/svgr.d.ts
  src/entities/product/productApi.ts
  src/entities/product/types.ts
  src/pages/home/index.ts
  src/pages/home/ui/HomePage.tsx
  src/shared/api/apiClient.ts
  src/shared/api/types.ts
  src/shared/assets/icons/index.ts
  src/shared/assets/icons/social/facebook.svg
  src/shared/assets/icons/social/instagram.svg
  src/shared/assets/icons/social/twitter.svg
  src/shared/assets/icons/social/youtube.svg
  src/shared/assets/images/logo.svg
  src/shared/config/constants.ts
  src/shared/ui/Logo.tsx
  src/widgets/footer/index.ts
  src/widgets/footer/ui/Footer.tsx
  src/widgets/header/index.ts
  src/widgets/header/ui/Header.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#95 [강대원] Sprint 5
  .github/pull-request-template.md
  .github/workflows/auto-label-assign.yml
  .gitignore
  README.md
  eslint.config.js
  index.html
  package.json
  src/App.css
  src/App.tsx
  src/assets/fonts/Pretendard-Black.otf
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard-Thin.otf
  src/assets/fonts/fonts.css
  src/assets/images/default/img_default.png
  src/assets/images/icons/arrow/arrow-left-active.svg
  src/assets/images/icons/arrow/arrow-left-inactive.svg
  src/assets/images/icons/arrow/arrow-right-active.svg
  src/assets/images/icons/arrow/arrow-right-inactive.svg
  src/assets/images/icons/heart/heart-active.svg
  src/assets/images/icons/heart/heart-inactive.svg
  src/assets/images/icons/search/search.svg
  src/assets/images/icons/sort/btn_sort.svg
  src/assets/images/logo/favicon.ico
  src/assets/images/logo/panda-market-logo.svg
  src/assets/images/social/facebook-logo.svg
  src/assets/images/social/instagram-logo.svg
  src/assets/images/social/twitter-logo.svg
  src/assets/images/social/youtube-logo.svg
  src/features/footer/Footer.tsx
  src/features/main/AddProductButton.tsx
  src/features/main/BestProducts.tsx
  src/features/main/LikeButtonWithCount.tsx
  src/features/main/Main.tsx
  src/features/main/Pagination.tsx
  src/features/main/ProductCard.tsx
  src/features/main/ProductSearchBar.tsx
  src/features/main/ProductsForSale.tsx
  src/features/main/SortByDropdown.tsx
  src/features/navbar/Navbar.tsx
  src/globalStyles.ts
  src/main.tsx
  src/services/ProductService.ts
  src/utils/axiosClient.ts
  src/utils/axiosDefault.ts
  src/utils/handler.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 매운맛🔥, 최종 제출

#100 [김지연] sprint5
  .editorconfig
  .gitignore
  .npmrc
  README.md
  biome.json
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  src/apis/fetch.ts
  src/apis/products.ts
  src/assets/font/Pretendard-Bold.subset.woff2
  src/assets/font/Pretendard-Medium.subset.woff2
  src/assets/font/Pretendard-Regular.subset.woff2
  src/assets/font/Pretendard-SemiBold.subset.woff2
  src/assets/header-logo.png
  src/assets/image/footer/facebook-logo.svg
  src/assets/image/footer/instagram-logo.svg
  src/assets/image/footer/twitter-logo.svg
  src/assets/image/footer/youtube-logo.svg
  src/assets/image/items/item-default.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ItemCard.tsx
  src/components/Logo.tsx
  src/components/Pagination.tsx
  src/components/SearchInput.tsx
  src/components/SortSelection.tsx
  src/error-page.tsx
  src/index.css
  src/main.tsx
  src/routes/items.tsx
  src/routes/root.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
  tsconfig.json
  tsconfig.node.json
  tsconfig.node.tsbuildinfo
  types/globals.d.ts
  types/product.ts
  vite.config.ts
Labels: 미완성🫠, 진행 중 🏃

#101 [김태훈] Sprint5
  sprint5/.gitignore
  sprint5/README.md
  sprint5/package-lock.json
  sprint5/package.json
  sprint5/public/favicon.ico
  sprint5/public/index.html
  sprint5/public/logo192.png
  sprint5/public/logo512.png
  sprint5/public/manifest.json
  sprint5/public/robots.txt
  sprint5/src/App.js
  sprint5/src/api/GetProductList.js
  sprint5/src/assets/Heart.png
  sprint5/src/assets/Tab.png
  sprint5/src/assets/facebook-logo.svg
  sprint5/src/assets/instagram-logo.svg
  sprint5/src/assets/market.png
  sprint5/src/assets/pandaLogo.png
  sprint5/src/assets/twitter-logo.svg
  sprint5/src/assets/youtube-logo.svg
  sprint5/src/component/Body.jsx
  sprint5/src/component/Footer.css
  sprint5/src/component/Footer.jsx
  sprint5/src/component/Header.css
  sprint5/src/component/Header.jsx
  sprint5/src/index.js
  sprint5/src/page/BestItem.jsx
  sprint5/src/page/itemCard.jsx
Labels: 미완성🫠, 진행 중 🏃

#110 [강대원] Sprint 6
  .gitignore
  .vite/deps/_metadata.json
  .vite/deps/package.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/images/home/bottom-banner-image.png
  src/assets/images/home/feature1-image.png
  src/assets/images/home/feature2-image.png
  src/assets/images/home/feature3-image.png
  src/assets/images/home/hero-image.png
  src/assets/images/icons/close/ic-X.svg
  src/globalStyles.ts
  src/hooks/useValidation.ts
  src/layouts/banner/Banner.tsx
  src/layouts/footer/Footer.tsx
  src/layouts/main/AddProductButton.tsx
  src/layouts/main/BestProducts.tsx
  src/layouts/main/IntroSection.tsx
  src/layouts/main/LikeButtonWithCount.tsx
  src/layouts/main/Main.tsx
  src/layouts/main/Pagination.tsx
  src/layouts/main/ProductCard.tsx
  src/layouts/main/ProductRegistration.tsx
  src/layouts/main/ProductSearchBar.tsx
  src/layouts/main/ProductsForSale.tsx
  src/layouts/navbar/Navbar.tsx
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/ItemsPage.tsx
  src/pages/RegistrationPage.tsx
  src/shared/Button.tsx
  src/shared/HashtagList.tsx
  src/shared/SortByDropdown.tsx
  yarn.lock
Labels: 매운맛🔥, 진행 중 🏃

#104 [강수정] sprint6
  판다마켓/react/my-app/package-lock.json
  판다마켓/react/my-app/package.json
  판다마켓/react/my-app/public/img/Component 2.png
  판다마켓/react/my-app/public/img/Component 3.png
  판다마켓/react/my-app/public/img/Group 19.png
  판다마켓/react/my-app/public/img/Vector.png
  판다마켓/react/my-app/public/img/bottom-banner-image.png
  판다마켓/react/my-app/public/img/btn_hidden.png
  판다마켓/react/my-app/public/img/facebook-logo.svg
  판다마켓/react/my-app/public/img/feature1-image.png
  판다마켓/react/my-app/public/img/feature2-image.png
  판다마켓/react/my-app/public/img/feature3-image.png
  판다마켓/react/my-app/public/img/google.png
  판다마켓/react/my-app/public/img/hero-image.png
  판다마켓/react/my-app/public/img/instagram-logo.svg
  판다마켓/react/my-app/public/img/twitter-logo.svg
  판다마켓/react/my-app/public/img/visible.png
  판다마켓/react/my-app/public/img/youtube-logo.svg
  판다마켓/react/my-app/src/App.js
  판다마켓/react/my-app/src/api/api.js
  판다마켓/react/my-app/src/common/Footer.jsx
  판다마켓/react/my-app/src/common/Header.js
  판다마켓/react/my-app/src/common/Product.js
  판다마켓/react/my-app/src/common/header.css
  판다마켓/react/my-app/src/common/img/Group19.png
  판다마켓/react/my-app/src/common/img/ic_heart.png
  판다마켓/react/my-app/src/common/img/img_default.png
  판다마켓/react/my-app/src/common/img/search.png
  판다마켓/react/my-app/src/container/Header.js
  판다마켓/react/my-app/src/img/Polygon.png
  판다마켓/react/my-app/src/img/search.png
  판다마켓/react/my-app/src/index.js
  판다마켓/react/my-app/src/pages/index.js
  판다마켓/react/my-app/src/pages/items/Item.js
  판다마켓/react/my-app/src/pages/items/ItemsPage.js
  판다마켓/react/my-app/src/pages/items/ltem.css
  판다마켓/react/my-app/src/pages/items/used.css
  판다마켓/react/my-app/src/pages/main/Main.jsx
  판다마켓/react/my-app/src/pages/main/MainLayout.js
  판다마켓/react/my-app/src/pages/main/MainPage.js
  판다마켓/react/my-app/src/pages/main/RealMain.css
  판다마켓/react/my-app/src/pages/main/RealMain.jsx
  판다마켓/react/my-app/src/pages/main/main.css
  판다마켓/react/my-app/src/pages/null/nullpage.js
  판다마켓/react/my-app/src/pages/registration/RegistrationPage.jsx
  판다마켓/react/my-app/src/pages/registration/registration.css
Labels: 매운맛🔥, 최종 제출
