Repository codeit-sprint-fullstack/3-sprint-mission-fe, pull requests merged in 2024-10, with the labels that each got.

#10 [김태훈]스프린트1,2
  Component 2.png
  Component 3.png
  btn_visibility_on_24px.png
  facebook-logo.svg
  favicon.ico
  feature1-image.png
  feature2-image.png
  feature3-image.png
  feature4-image .png
  hero-image.png
  index.html
  instagram-logo.svg
  item.css
  item.html
  login.css
  login.html
  logo.png
  newbee.css
  newbee.html
  panda-market-logo.png
  panda.css
  twitter-logo.svg
  youtube-logo.svg
  판다마켓.code-workspace
Labels: 매운맛🔥, 최종 제출

#12 [박수환]스프린트1,2
  css/button.css
  css/login.css
  css/reset.css
  css/signup.css
  css/style.css
  dir/faq.html
  dir/item.html
  dir/login.html
  dir/privacy.html
  dir/public.html
  dir/signup.html
  icon/facebook-logo.svg
  icon/google1.svg
  icon/google2.svg
  icon/google3.svg
  icon/instagram-logo.svg
  icon/kakao_icon.svg
  icon/pwicon1.svg
  icon/twitter-logo.svg
  icon/youtube-logo.svg
  image/panda-market-logo.png
  image/sprint2_로고.png
  image/네번째섹터.png
  image/다섯번째섹터.png
  image/두번째 섹터.png
  image/세번째 섹터.png
  image/첫번째섹터.png
  index.html
Labels: 매운맛🔥

#23 add:스프린트미션2
  Component 2.png
  Component 2@2x.png
  Component 2@3x.png
  Component 3.png
  Component 3@2x.png
  Component 3@3x.png
  FAQ.html
  Privacy Policy.html
  bottom-banner-image.png
  btn_visibility_off_24px.png
  facebook-logo.svg
  favicon.ico
  feature1-image.png
  feature2-image.png
  feature3-image.png
  hero-image.png
  index.html
  instagram-logo.svg
  login.html
  panda-market-logo.png
  panda.css
  panda2.css
  panda3.css
  signup.html
  twitter-logo.svg
  youtube-logo.svg
  구경하러가기.html
Labels: 매운맛🔥, 최종 제출

#25 [전준기] 스프린트1,2
  faq.html
  imgs/Component 2@2x.png
  imgs/Component 3@2x.png
  imgs/Img_home_01.png
  imgs/Img_home_03.png
  imgs/Img_home_top.png
  imgs/bottom-banner-image.png
  imgs/btn_visibility_on_24px.png
  imgs/eye-slash-solid.svg
  imgs/facebook-logo.svg
  imgs/feature2-image.png
  imgs/instagram-logo.svg
  imgs/panda-market-logo.png
  imgs/twitter-logo.svg
  imgs/youtube-logo.svg
  index.css
  index.html
  items.html
  login.css
  login.html
  privacy.html
  reset.css
  signup.html
Labels: 매운맛🔥, 최종 제출

#2 [김지연] 스프린트1,2
  .github/workflows/auto-label-assign.yml
  .gitignore
  404.html
  CONSTANS.js
  README.md
  _redirects
  biome.json
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/icon/show-off.svg
  images/icon/show-on.svg
  images/logo/favicon.ico
  images/logo/google-login.png
  images/logo/kakao-login.png
  images/logo/mb_panda-market-logo.png
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/instagram-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  pages/faq.html
  pages/items.html
  pages/privacy.html
  pages/sign-in.html
  pages/sign-up.html
  static/font/Pretendard-Bold.subset.woff2
  static/font/Pretendard-Medium.subset.woff2
  static/font/Pretendard-Regular.subset.woff2
  static/font/Pretendard-SemiBold.subset.woff2
  styles/base/animation.css
  styles/base/buttonBase.css
  styles/base/color.css
  styles/base/font.css
  styles/base/layout.css
  styles/base/preflight.css
  styles/base/variables.css
  styles/common.css
  styles/components/card.css
  styles/components/form.css
  styles/components/modal.css
  styles/home.css
  styles/sign-in.css
  styles/sign-up.css
Labels: 매운맛🔥, 최종 제출

#19 [하신혜] Sprint 1,2
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/Img_home_01.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/Img_home_02.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/Img_home_03.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/Img_home_bottom.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/Img_home_top.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/README.md
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/ROKAF Sans Medium.ttf
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/btn_visibility_on_24px.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/google_logo.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/ic_facebook.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/ic_instagram.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/ic_twitter.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/ic_youtube.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/index.html
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/join.css
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/join.html
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/join.js
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/kakaotalk_logo.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/login.html
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/login.js
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/login_style.css
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/pandalogo2.png
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/pretendard.css
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/reset.css
  스프린트미션_1&2_하신혜/스프린트 미션_1&2_하신혜/style.css
Labels: 매운맛🔥, 최종 제출

#21 [최혜지] sprint1, 2
  css/books.png
  css/eye-icon.png
  css/facebook.svg
  css/google.png
  css/instagram.svg
  css/kakao.png
  css/login-button.png
  css/login-logo.png
  css/login.css
  css/logo.png
  css/panda-bottom.png
  css/panda.png
  css/reset.css
  css/search.png
  css/show-button.png
  css/sign-up.css
  css/style.css
  css/tshirt.png
  css/x.svg
  css/youtube.svg
  index.html
  login.html
  login.js
  sign-up.html
  sign-up.js
Labels: 매운맛🔥

#26 [김성수] sprint1,2
  Component 2.png
  Component 2@2x.png
  Component 2@3x.png
  Component 3.png
  Component 3@2x.png
  Component 3@3x.png
  bottom-banner-image.png
  btn_visibility_on_24px.png
  facebook-logo.svg
  favicon.ico
  feature1-image.png
  feature2-image.png
  feature3-image.png
  hero-image.png
  index.html
  instagram-logo.svg
  login.css
  login.html
  logo.png
  panda-market-logo.png
  panda.css
  signup.html
  singup.css
  twitter-logo.svg
  youtube-logo.svg
  객체.js
Labels: 매운맛🔥, 미완성🫠

#27 [강대원] sprint 1 + 2
  faq.html
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/login/btn_visibility_off_24px.svg
  images/login/google.png
  images/login/kakao.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/logo/panda-market-logo.svg
  images/social/facebook-logo.svg
  images/social/instagram-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.css
  index.html
  items.html
  login-page/login.css
  login-page/login.html
  privacy.html
  signup-page/signup.css
  signup-page/signup.html
  styles/reset.css
Labels: 매운맛🔥, 최종 제출

#20 [정유석] sprint 1+2
  README.md
  assets/Img_home_01.png
  assets/Img_home_02.png
  assets/Img_home_03.png
  assets/Img_home_bottom.png
  assets/Img_home_top.png
  assets/font/Pretendard-Regular.woff
  assets/font/ROKAF_Sans_Bold.ttf
  assets/font/ROKAF_Sans_Medium.ttf
  assets/google.png
  assets/hide-pw.png
  assets/ic_facebook.svg
  assets/ic_instagram.svg
  assets/ic_twitter.svg
  assets/ic_youtube.svg
  assets/kakao.png
  assets/login-logo.png
  assets/logo.png
  assets/show-pw.png
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  scripts/script.js
  scripts/signup(orig).js
  scripts/signup.js
  signup.html
  styles/login.css
  styles/main.css
  styles/media_query.css
  styles/reset.css
  styles/signup.css
Labels: 매운맛🔥, 최종 제출

#3 [이현우] sprint1,2
  .gitignore
  README.md
  faq/index.html
  images/common/facebook-logo.svg
  images/common/instagram-logo.svg
  images/common/twitter-logo.svg
  images/common/youtube-logo.svg
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/login/eye.slash.svg
  images/login/eye.svg
  images/login/google.svg
  images/login/kakao.svg
  images/panda-market-logo.svg
  images/panda.svg
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  screenshots/landing-page-mobile.png
  screenshots/landing-page-pc.png
  screenshots/login-page-focus-pc.png
  screenshots/login-page-mobile.png
  screenshots/login-page-pc.png
  screenshots/login-page-toggle-pw-pc.png
  screenshots/signin-page-mobile.png
  screenshots/signin-page-pc.png
  scripts/login.js
  signup/index.html
  styles/home.css
  styles/login.css
  styles/reset.css
Labels: 매운맛🔥, 최종 제출

#5 [김두봉] sprint1,2
  faq/main.html
  fonts/ROKAF Sans Bold.ttf
  fonts/ROKAF Sans Medium.ttf
  fonts/ROKAF-Sans-Bold.woff
  fonts/ROKAF-Sans-Medium.woff
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/login/btn_visibility_on_24px.png
  images/login/btn_visibility_on_24px.svg
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/google.svg
  images/social/instagram-logo.svg
  images/social/kakao.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  items/main.html
  javascript/panda.js
  login/login.html
  login/main.html
  membership/signup.html
  panda.css
  privacy/main.html
Labels: 매운맛🔥, 최종 제출

#15 [임예지] sprint 1&2
  팬더마켓/faq/faq.html
  팬더마켓/images/home/bottom-banner-image.png
  팬더마켓/images/home/feature1-image.png
  팬더마켓/images/home/feature2-image.png
  팬더마켓/images/home/feature3-image.png
  팬더마켓/images/home/hero-image.png
  팬더마켓/images/logo/favicon.ico
  팬더마켓/images/logo/panda-market-logo.png
  팬더마켓/images/social/btn_visibility_off_24px.png
  팬더마켓/images/social/facebook.png
  팬더마켓/images/social/google.png
  팬더마켓/images/social/instagram.png
  팬더마켓/images/social/kakaotalk.png
  팬더마켓/images/social/twitter.png
  팬더마켓/images/social/youtube.png
  팬더마켓/index.html
  팬더마켓/itmes/itmes.html
  팬더마켓/login/login.css
  팬더마켓/login/login.html
  팬더마켓/privacy/privacy.html
  팬더마켓/reset.css
  팬더마켓/signup/signup.css
  팬더마켓/signup/signup.html
  팬더마켓/style.css
Labels: 매운맛🔥

#29 스프린트 미션입니다
  .github/판다마켓 스프린트 미션/bottom-banner-image.png
  .github/판다마켓 스프린트 미션/facebook-logo.svg
  .github/판다마켓 스프린트 미션/feature1-image.png
  .github/판다마켓 스프린트 미션/feature2-image.png
  .github/판다마켓 스프린트 미션/feature3-image.png
  .github/판다마켓 스프린트 미션/googlelogo.png
  .github/판다마켓 스프린트 미션/hero-image.png
  .github/판다마켓 스프린트 미션/index.html
  .github/판다마켓 스프린트 미션/instagram-logo.svg
  .github/판다마켓 스프린트 미션/kakaologo.png
  .github/판다마켓 스프린트 미션/login.css
  .github/판다마켓 스프린트 미션/login.html
  .github/판다마켓 스프린트 미션/panda-market-logo.png
  .github/판다마켓 스프린트 미션/panda.css
  .github/판다마켓 스프린트 미션/pull-request-template.md
  .github/판다마켓 스프린트 미션/signup.css
  .github/판다마켓 스프린트 미션/signup.html
  .github/판다마켓 스프린트 미션/twitter-logo.svg
  .github/판다마켓 스프린트 미션/youtube-logo.svg
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR

#4 [함헌규] 스프린트 미션 1&2
  .github/workflows/auto-label-assign.yml
  .gitignore
  README.md
  assets/images/common/logo.png
  assets/images/home/2.popular_product.jpg
  assets/images/home/3.search_product.jpg
  assets/images/home/4.register_product.jpg
  assets/images/home/Img_home_bottom.png
  assets/images/home/Img_home_top.png
  assets/images/home/ic_facebook.png
  assets/images/home/ic_instagram.png
  assets/images/home/ic_twitter.png
  assets/images/home/ic_youtube.png
  assets/images/login&signup/google.png
  assets/images/login&signup/kakaotalk.png
  assets/styles/home.css
  assets/styles/reset.css
  assets/styles/sign.css
  css/_login.css
  css/_reset.css
  css/_style.css
  css/font/Pretendard-Regular.woff
  css/font/Pretendard-Regular.woff2
  faq.html
  faq/index.html
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/big_logo.png
  img/google_icon.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/kakao_icon.png
  img/logo.png
  img/look.png
  img/look.svg
  img/look2.svg
  index.html
  items.html
  items/index.html
  js/form.js
  login.html
  login/index.html
  privacy.html
  privacy/index.html
  signup.html
  signup/index.html
Labels: 매운맛🔥, 최종 제출

#7 [정해찬] Sprint 1,2
  .DS_Store
  mission2/.DS_Store
  mission2/faq.html
  mission2/img/btn_visibility_off_24px.png
  mission2/img/facebook.png
  mission2/img/google.png
  mission2/img/insta.png
  mission2/img/katalk.png
  mission2/img/landing_header.png
  mission2/img/logo.png
  mission2/img/panda.png
  mission2/img/sec1_img.png
  mission2/img/sec2_img.png
  mission2/img/sec3_img.png
  mission2/img/sec5_img.png
  mission2/img/twitter.png
  mission2/img/youtube.png
  mission2/img/판다 얼굴.png
  mission2/index.html
  mission2/items.html
  mission2/landing.css
  mission2/login.html
  mission2/privacy.html
  mission2/signup.html
  mission2/user.css
Labels: 매운맛🔥, 최종 제출

#11 [정리은]Sprint1,2
  스프린트 미션/images/free-icon-eye-8833096.png
  스프린트 미션/images/free-icon-hidden-7578269.png
  스프린트 미션/images/home/bottom-banner-image.png
  스프린트 미션/images/home/feature1-image.png
  스프린트 미션/images/home/feature2-image.png
  스프린트 미션/images/home/feature3-image.png
  스프린트 미션/images/home/hero-image.png
  스프린트 미션/images/icon-eye.png
  스프린트 미션/images/logo/favicon.ico
  스프린트 미션/images/logo/panda-market-logo.png
  스프린트 미션/images/social/facebook-logo.svg
  스프린트 미션/images/social/instagram-logo.svg
  스프린트 미션/images/social/twitter-logo.svg
  스프린트 미션/images/social/youtube-logo.svg
  스프린트 미션/images/구글.png
  스프린트 미션/images/카톡.png
  스프린트 미션/index.html
  스프린트 미션/login.css
  스프린트 미션/login.html
  스프린트 미션/panda.css
  스프린트 미션/reset.css
  스프린트 미션/signup.html
Labels: 매운맛🔥

#24 [김혁진] sprint1&2
  panda/bottom-banner-image.png
  panda/favicon.ico
  panda/feature1-image.png
  panda/feature2-image.png
  panda/feature3-image.png
  panda/google.png
  panda/hero-image.png
  panda/ic_facebook.png
  panda/ic_instagram.png
  panda/ic_twitter.png
  panda/ic_youtube.png
  panda/index.html
  panda/kakao.png
  panda/login.css
  panda/login.html
  panda/panda-market-logo.png
  panda/pandaMarket.css
  panda/signup.html
Labels: 매운맛🔥, 미완성🫠

#28 [배호근] sprint1,2
  bottom-banner-image.png
  facebook-logo.svg
  feature1-image.png
  feature2-image.png
  feature3-image.png
  hero-image.png
  index.html
  instagram-logo.svg
  panda-market-logo.png
  start-login.css
  start-login.html
  start-sign-up.css
  start-sign-up.html
  start.css
  start.html
  twitter-logo.svg
  youtube-logo.svg
Labels: 매운맛🔥, 미완성🫠

#44 [박수환] sprint3
  .vscode/settings.json
  css/button.css
  css/login.css
  css/main-page-css-file/footer.css
  css/main-page-css-file/header.css
  css/main-page-css-file/main.css
  css/main-page-css-file/media-qu.css
  css/reset.css
  css/signup.css
  css/style.css
  dir/login.html
  dir/signup.html
  icon/pwicon2.svg
  index.html
  js/login.js
  js/sign.js
Labels: 매운맛🔥, 진행 중 🏃

#39 [전준기] sprint3
  index.css
  index.html
  login.css
  login.html
  login.js
  signUp.js
  signup.html
Labels: 매운맛🔥, 미완성🫠

#43 [김두봉] sprint3
  .github/workflows/auto-label-assign.yml
  .vscode/settings.json
  README.md
  faq.html
  faq/main.html
  fonts/ROKAF Sans Bold.ttf
  fonts/ROKAF Sans Medium.ttf
  fonts/ROKAF-Sans-Bold.woff
  fonts/ROKAF-Sans-Medium.woff
  index.html
  items.html
  items/main.html
  javascript/login.js
  javascript/panda.js
  javascript/signup.js
  login.html
  login/login.html
  login/main.html
  membership/signup.html
  panda.css
  privacy.html
  privacy/main.html
  signup.html
  styles/auth.css
  styles/global.css
  styles/home.css
  styles/signup.css
Labels: 매운맛🔥, 최종 제출

#40 [이현우] sprint3
  .gitignore
  README.md
  faq/index.html
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  scripts/common.js
  scripts/constants/userData.js
  scripts/constants/validityMessage.js
  scripts/ui/component.js
  scripts/utils/fadeEffect.js
  scripts/validation.js
  signup/index.html
  styles/home.css
  styles/login.css
  styles/reset.css
  styles/variables.css
Labels: 매운맛🔥, 진행 중 🏃

#41 [임예지] sprint3
  README.md
  팬더마켓/images/social/btn_visibility_off.png
  팬더마켓/images/social/btn_visibility_on.png
  팬더마켓/index.html
  팬더마켓/login/login.css
  팬더마켓/login/login.html
  팬더마켓/login/login.js
  팬더마켓/signup/signup.css
  팬더마켓/signup/signup.html
  팬더마켓/signup/signup.js
  팬더마켓/style.css
Labels: 미완성🫠, 순한맛🐑

#48 [강대원] sprint3
  assets/images/auth/btn_visibility_off_24px.svg
  assets/images/auth/btn_visibility_on_24px.svg
  assets/images/auth/google.png
  assets/images/auth/kakao.png
  assets/images/home/bottom-banner-image.png
  assets/images/home/feature1-image.png
  assets/images/home/feature2-image.png
  assets/images/home/feature3-image.png
  assets/images/home/hero-image.png
  assets/images/logo/favicon.ico
  assets/images/logo/panda-market-logo.png
  assets/images/logo/panda-market-logo.svg
  assets/images/social/facebook-logo.svg
  assets/images/social/instagram-logo.svg
  assets/images/social/twitter-logo.svg
  assets/images/social/youtube-logo.svg
  common/css/modal.css
  common/css/validation.css
  common/js/form-validation.js
  common/js/modal.js
  common/js/password-visibility.js
  common/js/regex.js
  data/users.js
  index.css
  index.html
  login-page/login.html
  pages/auth/login/login.css
  pages/auth/login/login.html
  pages/auth/login/login.js
  pages/auth/signup/signup.css
  pages/auth/signup/signup.html
  pages/auth/signup/signup.js
  signup-page/signup.html
  styles/common.css
Labels: 매운맛🔥, 미완성🫠

#47 [정유석] sprint3
  assets/og-image.jpg
  faq.html
  index.html
  items.html
  login.html
  package.json
  privacy.html
  scripts/login.js
  scripts/script.js
  scripts/signup(orig).js
  scripts/signup.js
  scripts/userdata.js
  signup.html
  styles/login.css
  styles/main.css
  styles/media_query.css
  styles/signup.css
Labels: 매운맛🔥, 제출일 이후 제출한PR, 진행 중 🏃

#31 [최혜지] sprint3
  css/login.css
  css/sign-up.css
  css/랜딩-이미지.png
  index.html
  login.html
  login.js
  sign-up.html
  sign-up.js
Labels: 미완성🫠

#34 [함헌규] sprint3
  assets/scripts/constants/messages.js
  assets/scripts/constants/names.js
  assets/scripts/constants/userData.js
  assets/scripts/constants/validationValues.js
  assets/scripts/core/sign.js
  assets/scripts/login.js
  assets/scripts/signup.js
  assets/scripts/utils/query.js
  assets/scripts/utils/validator.js
  assets/styles/home.css
  assets/styles/sign.css
  docs/sprint3.md
  index.html
  login/index.html
  signup/index.html
Labels: 매운맛🔥, 최종 제출

#37 [정리은]sprint3
  스프린트 미션/login.css
  스프린트 미션/login.html
  스프린트 미션/login.js
  스프린트 미션/signup.html
  스프린트 미션/signup.js
Labels: 매운맛🔥

#50 [정해찬] sprint 3
  .DS_Store
  pandamarket/.DS_Store
  pandamarket/faq.html
  pandamarket/img/btn_visibility_off_24px.png
  pandamarket/img/facebook.png
  pandamarket/img/google.png
  pandamarket/img/insta.png
  pandamarket/img/katalk.png
  pandamarket/img/landing_header.png
  pandamarket/img/logo.png
  pandamarket/img/panda.png
  pandamarket/img/sec1_img.png
  pandamarket/img/sec2_img.png
  pandamarket/img/sec3_img.png
  pandamarket/img/sec5_img.png
  pandamarket/img/twitter.png
  pandamarket/img/youtube.png
  pandamarket/img/판다 얼굴.png
  pandamarket/index.html
  pandamarket/items.html
  pandamarket/landing.css
  pandamarket/login.html
  pandamarket/privacy.html
  pandamarket/signup.html
  pandamarket/user.css
  pandamarket/user.js
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR

#51 [김혁진] sprint 3
  css/login.css
  css/pandaMarket.css
  html/index.html
  html/login.html
  html/signup.html
  img/bottom-banner-image.png
  img/favicon.ico
  img/feature1-image.png
  img/feature2-image.png
  img/feature3-image.png
  img/google.png
  img/hero-image.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/kakao.png
  img/panda-market-logo.png
  js/login.js
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR

#58 [이현우] sprint4
  .editorconfig
  .github/workflows/auto-label-assign.yml
  README.md
  apis/ArticleService.js
  apis/ProductService.js
  apis/constants.js
  apis/demo.html
  apis/main.js
  apis/util.js
Labels: 매운맛🔥, 최종 제출

#61 [임예지] sprint4
  팬더마켓/apis/ArticleService.js
  팬더마켓/apis/Main.js
  팬더마켓/apis/ProductService.js
  팬더마켓/apis/package.json
  팬더마켓/index.html
  팬더마켓/login/login.css
  팬더마켓/login/login.html
  팬더마켓/login/login.js
  팬더마켓/main.css
  팬더마켓/root.css
  팬더마켓/signup/signup.css
  팬더마켓/signup/signup.html
  팬더마켓/signup/signup.js
Labels: 매운맛🔥, 미완성🫠, 진행 중 🏃

#69 [배진한] Sprint4
  apies/ArticleService.js
  apies/ProductService.js
  apies/main.js
  apies/package.json
Labels: 매운맛🔥, 순한맛🐑, 최종 제출

#74 [박수환] sprint4
  css/main-page-css-file/main.css
  css/main-page-css-file/media-qu.css
  dir/login.html
  dir/signup.html
  index.html
  js/login.js
  js/sign.js
  sprint4미션/ArticleService.js
  sprint4미션/ProductService.js
  sprint4미션/main.js
Labels: 매운맛🔥, 최종 제출

#72 [최종훈] sprint 4
  FAQ.html
  Privacy Policy.html
  css/index.css
  css/login.css
  css/panda.css
  css/panda2.css
  css/panda3.css
  css/signup.css
  html/FAQ.html
  html/Privacy Policy.html
  html/index.html
  html/login.html
  html/signup.html
  html/구경하러가기.html
  img/Component 2.png
  img/Component 2@2x.png
  img/Component 2@3x.png
  img/Component 3.png
  img/Component 3@2x.png
  img/Component 3@3x.png
  img/bottom-banner-image.png
  img/btn_visibility_off_24px.png
  img/facebook-logo.svg
  img/favicon.ico
  img/feature1-image.png
  img/feature2-image.png
  img/feature3-image.png
  img/hero-image.png
  img/instagram-logo.svg
  img/panda-market-logo.png
  img/twitter-logo.svg
  img/youtube-logo.svg
  index.html
  javascript/ArticleService.js
  javascript/ProductService.js
  javascript/login.js
  javascript/main.js
  javascript/signup.js
  login.css
  login.html
  package.json
  signup.html
  signup.js
  구경하러가기.html
Labels: 매운맛🔥, 최종 제출

#76 Basic 박지환 mission4
  css/index.css
  css/login.css
  css/signup.css
  html/index.html
  html/login.html
  html/signup.html
  img/bottom-banner-image.png
  img/facebook-logo.svg
  img/feature1-image.png
  img/feature2-image.png
  img/feature3-image.png
  img/googlelogo.png
  img/hero-image.png
  img/instagram-logo.svg
  img/kakaologo.png
  img/panda-market-logo.png
  img/twitter-logo.svg
  img/youtube-logo.svg
  js/ArticleService.js
  js/ProductService.js
  js/login.js
  js/main.js
  js/packge.json
  js/signup.js
Labels: 매운맛🔥, 최종 제출

#70 [강수정] sprint4
  .DS_Store
  .vscode/settings.json
  판다마켓/.DS_Store
  판다마켓/api/common/common.js
  판다마켓/api/common/constant.js
  판다마켓/api/main.js
  판다마켓/api/package.json
  판다마켓/api/services/ArticleService.js
  판다마켓/api/services/ProductService.js
  판다마켓/img/btn_hidden.png
  판다마켓/img/visible.png
  판다마켓/sub/.DS_Store
  판다마켓/sub/login/.DS_Store
  판다마켓/sub/login/index.html
  판다마켓/sub/login/index.js
  판다마켓/sub/login/login.html
  판다마켓/sub/login/loginstyle.css
  판다마켓/sub/signup/.DS_Store
  판다마켓/sub/signup/index.html
  판다마켓/sub/signup/index.js
  판다마켓/sub/signup/signup.html
  판다마켓/sub/signup/signupstyle.css
Labels: 매운맛🔥, 최종 제출

#60 [정유석] sprint 4
  README.md
  index.html
  scripts/main.js
  services/articleService(axios).js
  services/articleService.js
  services/productService(axios).js
  services/productService.js
  signup.html
  styles/login.css
  styles/media_query.css
Labels: 순한맛🐑, 최종 제출

#73 [임예지] sprint4
  팬더마켓/apis/ArticleService.js
  팬더마켓/apis/Main.js
  팬더마켓/apis/ProductService.js
  팬더마켓/index.html
  팬더마켓/items/itmes.html
  팬더마켓/main.css
Labels: 매운맛🔥, 최종 제출

#78 [김태훈] sprint4
  CSS/item-page.css
  CSS/login-page.css
  CSS/main-page.css
  CSS/signup.css
  HTMl/index.html
  HTMl/item-page.html
  HTMl/login-page.html
  HTMl/signup.html
  javaScript/ArticleList.js
  javaScript/login-page.js
  javaScript/main.js
  javaScript/package.json
  javaScript/productList.js
  javaScript/signup.js
  png/Component 2.png
  png/Component 3.png
  png/btn_visibility_on_24px.png
  png/facebook-logo.svg
  png/favicon.ico
  png/feature1-image.png
  png/feature2-image.png
  png/feature3-image.png
  png/feature4-image .png
  png/hero-image.png
  png/instagram-logo.svg
  png/logo.png
  png/panda-market-logo.png
  png/twitter-logo.svg
  png/youtube-logo.svg
Labels: 최종 제출

#96 정유석 Sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/apis/ProductService.js
  src/assets/font/Pretendard-Regular.woff
  src/assets/font/ROKAF_Sans_Bold.ttf
  src/assets/font/ROKAF_Sans_Medium.ttf
  src/assets/images/ic_facebook.svg
  src/assets/images/ic_instagram.svg
  src/assets/images/ic_twitter.svg
  src/assets/images/ic_youtube.svg
  src/assets/images/like-icon.png
  src/assets/images/logo.png
  src/assets/images/page_left_arrow.png
  src/assets/images/page_right_arrow.png
  src/assets/images/placeholder.png
  src/assets/images/search.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.module.css
  src/components/Main/Main.js
  src/components/Main/Main.module.css
  src/components/Nav/Nav.js
  src/components/Nav/Nav.module.css
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.module.css
  src/components/Pagination/Pagination_copy.js
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.module.css
  src/components/ProductList/BestProductList(반응형적용전백업).js
  src/components/ProductList/BestProductList.js
  src/components/ProductList/BestProductList.module.css
  src/components/ProductList/onSalesProductList(반응형적용전백업).js
  src/components/ProductList/onSalesProductList.js
  src/components/ProductList/onSalesProductList.module.css
  src/hooks/useMediaQuery.js
  src/index.js
  src/media_query.css
Labels: 미완성🫠, 순한맛🐑

#87 [배진한] Sprint5
  sprint5/.gitignore
  sprint5/package-lock.json
  sprint5/package.json
  sprint5/public/index.html
  sprint5/public/manifest.json
  sprint5/public/robots.txt
  sprint5/src/API/api.js
  sprint5/src/API/endpoint.js
  sprint5/src/App.css
  sprint5/src/App.js
  sprint5/src/components/Footer/index.css
  sprint5/src/components/Footer/index.js
  sprint5/src/components/Header/index.css
  sprint5/src/components/Header/index.js
  sprint5/src/img/favicon.ico
  sprint5/src/img/icons/Vector.png
  sprint5/src/img/icons/heart.png
  sprint5/src/img/icons/left.png
  sprint5/src/img/icons/menu.png
  sprint5/src/img/icons/right.png
  sprint5/src/img/panda-market-logo.png
  sprint5/src/img/social/ic_facebook.png
  sprint5/src/img/social/ic_instargram.png
  sprint5/src/img/social/ic_twitter.png
  sprint5/src/img/social/ic_youtube.png
  sprint5/src/index.css
  sprint5/src/index.js
  sprint5/src/pages/ItemsPage/BestProds/index.css
  sprint5/src/pages/ItemsPage/BestProds/index.js
  sprint5/src/pages/ItemsPage/EmptyBox/index.js
  sprint5/src/pages/ItemsPage/Prods/index.css
  sprint5/src/pages/ItemsPage/Prods/index.js
  sprint5/src/pages/ItemsPage/index.css
  sprint5/src/pages/ItemsPage/index.js
  sprint5/src/reportWebVitals.js
Labels: 순한맛🐑, 최종 제출

#86 [박수환] sprint5
  react-psh-sprint5/.gitignore
  react-psh-sprint5/README.md
  react-psh-sprint5/eslint.config.js
  react-psh-sprint5/index.html
  react-psh-sprint5/package-lock.json
  react-psh-sprint5/package.json
  react-psh-sprint5/src/App.css
  react-psh-sprint5/src/App.jsx
  react-psh-sprint5/src/api/getProductsList.jsx
  react-psh-sprint5/src/components/AllItem.jsx
  react-psh-sprint5/src/components/BestItem.jsx
  react-psh-sprint5/src/components/BodyMain.jsx
  react-psh-sprint5/src/components/Footer.jsx
  react-psh-sprint5/src/components/Header.jsx
  react-psh-sprint5/src/css/AllItem.css
  react-psh-sprint5/src/css/BestItem.css
  react-psh-sprint5/src/css/Footer.css
  react-psh-sprint5/src/css/Header.css
  react-psh-sprint5/src/css/button.css
  react-psh-sprint5/src/css/reset.css
  react-psh-sprint5/src/icon/btn_sort.svg
  react-psh-sprint5/src/icon/facebook-logo.svg
  react-psh-sprint5/src/icon/instagram-logo.svg
  react-psh-sprint5/src/icon/twitter-logo.svg
  react-psh-sprint5/src/icon/youtube-logo.svg
  react-psh-sprint5/src/image/PandaLogo.png
  react-psh-sprint5/src/index.css
  react-psh-sprint5/src/main.jsx
  react-psh-sprint5/vite.config.js
Labels: 매운맛🔥, 미완성🫠
