Repository codeit-sprint-fullstack/3-sprint-mission-fe, pull requests merged in 2024-12, with the labels that each got.

#115 [강대원] sprint 8
  .eslintrc.json
  .gitignore
  .prettierrc
  app/fonts/PretendardVariable.woff2
  app/globals.css
  app/layout.tsx
  app/not-found.tsx
  app/page.tsx
  app/post/[id]/edit/page.tsx
  app/post/[id]/page.tsx
  app/post/create/page.tsx
  app/post/page.tsx
  components/common/button/BackButton.tsx
  components/common/button/CommonBtn.tsx
  components/common/dropdown/PostAndCommentActionsDropdown.tsx
  components/common/footer/Footer.tsx
  components/common/nav/Nav.tsx
  components/post/BestPost/BestPost.tsx
  components/post/BestPost/BestPostCard.tsx
  components/post/BestPost/BestPostContent.tsx
  components/post/BestPost/BestPostTitle.tsx
  components/post/PostCreateAndEdit/PostEditor.tsx
  components/post/PostCreateAndEdit/PostEditorTitle.tsx
  components/post/PostDetail/CommentInput.tsx
  components/post/PostDetail/CommentList.tsx
  components/post/PostDetail/PostDetailContent.tsx
  components/post/PostList/PostList.tsx
  components/post/PostList/PostListCard.tsx
  components/post/PostList/PostListTitle.tsx
  mock/bestPostData.ts
  mock/postData.ts
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/icons/ic_back@2x.png
  public/icons/ic_heart.svg
  public/icons/ic_kebab.png
  public/icons/ic_profile.png
  public/icons/ic_search.svg
  public/icons/sns/ic_facebook.png
  public/icons/sns/ic_instagram.png
  public/icons/sns/ic_twitter.png
  public/icons/sns/ic_youtube.png
  public/images/badge/img_badge.png
  public/images/btn_sort.png
  public/images/laptop.png
  public/images/logo/logo.svg
  public/images/logo/logo_mobile.png
  tailwind.config.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠, 최종 제출

#121 [박수환] Sprint8
  .eslintrc.json
  .gitignore
  components/ArticleCommentDropDown.js
  components/ArticleDetail.js
  components/ArticleDropDown.js
  components/BestItem.js
  components/BestItemList.js
  components/DropDown.js
  components/Header.js
  components/PostList.js
  components/PostListAll.js
  components/SearchInput.js
  components/UpdateMain.js
  components/WriteButton.js
  components/WriteMain.js
  components/post.js
  css/BestItem.module.css
  css/BestItemList.module.css
  css/Dropdown.module.css
  css/Header.module.css
  css/Post.module.css
  css/PostList.module.css
  css/SearchInput.module.css
  css/Write.module.css
  css/WriteMain.module.css
  css/articleDetail.module.css
  jsconfig.json
  lib/api.js
  lib/axios.js
  netlify.toml
  next.config.mjs
  package-lock.json
  package.json
  pages/404.js
  pages/[id]/article.js
  pages/[id]/articleUpdate.js
  pages/_app.js
  pages/_document.js
  pages/articleWrite.js
  pages/index.js
  public/images/BestImage.png
  public/images/PandaLogo.png
  public/images/bestitemimage.png
  public/images/dropdown.png
  public/images/dropdownbutton.png
  public/images/heart.png
  public/images/heartIcon.png
  public/images/noComment.png
  public/images/return.png
  public/images/searchIcon.png
  public/images/userIcon.png
  styles/global.css
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR

#124 [전준기]-sprint8
  .eslintrc.json
  .gitignore
  README.md
  components/Article.js
  components/Article.module.css
  components/ArticleDetail.js
  components/ArticleDetail.module.css
  components/ArticleList.js
  components/ArticleList.module.css
  components/BestArticle.js
  components/BestArticle.module.css
  components/BestArticleList.js
  components/BestArticleList.module.css
  components/Comment.js
  components/Comment.module.css
  components/CommentLayout.js
  components/CommentLayout.module.css
  components/CommentList.js
  components/CommentList.module.css
  components/Footer.js
  components/Footer.module.css
  components/Header.js
  components/Header.module.css
  components/InputComment.js
  components/InputComment.module.css
  components/NoComment.js
  components/NoComment.module.css
  components/OrderDropDown.js
  components/OrderDropDown.module.css
  components/UpdateDropDown.js
  components/UpdateDropDown.module.css
  jsconfig.json
  lib/axios.js
  lib/formatDate.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/article/[id].js
  pages/createArticle.js
  pages/index.js
  public/imgs/Img_reply_empty.png
  public/imgs/facebook-logo.svg
  public/imgs/ic_back.png
  public/imgs/ic_heart.png
  public/imgs/ic_kebab.png
  public/imgs/ic_search.png
  public/imgs/imgExample.png
  public/imgs/instagram-logo.svg
  public/imgs/panda-market-logo.png
  public/imgs/twitter-logo.svg
  public/imgs/userProfileImg.png
  public/imgs/youtube-logo.svg
  styles/article.module.css
  styles/createArticle.module.css
  styles/global.css
  styles/index.module.css
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR

#117 [정해찬] sprint 8
  .gitignore
  next_sprint/.eslintrc.json
  next_sprint/.gitignore
  next_sprint/README.md
  next_sprint/components/Button.js
  next_sprint/components/DropDown.js
  next_sprint/components/Footer.js
  next_sprint/components/Header.js
  next_sprint/jsconfig.json
  next_sprint/next.config.mjs
  next_sprint/package-lock.json
  next_sprint/package.json
  next_sprint/pages/_app.js
  next_sprint/pages/_document.js
  next_sprint/pages/api/api.js
  next_sprint/pages/community/community.js
  next_sprint/pages/community/patching.js
  next_sprint/pages/community/posting.js
  next_sprint/pages/details/[id].js
  next_sprint/pages/index.js
  next_sprint/pages/login.js
  next_sprint/pages/market.js
  next_sprint/postcss.config.mjs
  next_sprint/public/favicon.ico
  next_sprint/public/file.svg
  next_sprint/public/globe.svg
  next_sprint/public/img/back_icon.png
  next_sprint/public/img/btn_dropDown.png
  next_sprint/public/img/default_img.png
  next_sprint/public/img/drop_arrow.png
  next_sprint/public/img/empty.png
  next_sprint/public/img/facebook.png
  next_sprint/public/img/img_badge.png
  next_sprint/public/img/insta.png
  next_sprint/public/img/panda_logo.png
  next_sprint/public/img/search_icon.png
  next_sprint/public/img/twitter.png
  next_sprint/public/img/user_profile.png
  next_sprint/public/img/youtube.png
  next_sprint/public/next.svg
  next_sprint/public/vercel.svg
  next_sprint/public/window.svg
  next_sprint/styles/globals.css
  next_sprint/tailwind.config.js
Labels: 매운맛🔥, 제출일 이후 제출한PR, 최종 제출

#133 [김지연] sprint8
  .gitignore
  components.json
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/icon/ic_facebook.svg
  public/icon/ic_instagram.svg
  public/icon/ic_twitter.svg
  public/icon/ic_youtube.svg
  public/images/Img_feature_01.png
  public/images/Img_feature_02.svg
  public/images/Img_feature_03.png
  public/images/Img_home_bottom.svg
  public/images/Img_home_top.svg
  public/logo/pandamarket_logo_icon.png
  public/logo/pandamarket_logo_text.png
  src/app/PretendardVariable.woff2
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/main/FeatureCard.tsx
  src/components/main/HeroCard.tsx
  src/lib/utils.ts
  tailwind.config.ts
  tsconfig.json
Labels: 미완성🫠, 제출일 이후 제출한PR, 진행 중 🏃
